### ISSUE TITLE
okio update leads to NoSuchMethodError

### ISSUE THREAD

**Issue by dvallant** [gesellix/docker-client#962]
Since the update of okio from 3.15.0 to 3.16.0 (#891) docker-client can no longer be used (at least in a pure java application). Calling any function (e.g. `dockerClient.info().getContent()`) leads to `java.lang.NoSuchMethodError: 'okio.Socket okio.Okio.socket(java.net.Socket)'`.

Manually downgrading okio to 3.15.0 fixes the problem.

**Comment by gesellix** [comment]
I think this might be a Maven specific issue (see more over there about differences between Gradle's and Maven's dependency resolution: https://jakewharton.com/nonsensical-maven-is-still-a-gradle-problem/).

Given a pom.xml with the following dependencies:

```xml
  <dependencies>
    <dependency>
      <groupId>de.gesellix</groupId>
      <artifactId>docker-client</artifactId>
      <version>2025-11-01T13-00-00-groovy-4</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <version>2.0.17</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
```

The dependency graph looks like this, note the highlighted `okio-jvm` version conflict between 3.16.2 and 3.7.0:

<img width="3726" height="3006" alt="Image" src="https://github.com/user-attachments/assets/974e5cf3-3287-47c6-a861-ab374d5eb127" />

Adding a direct dependency on okio changes the dependency graph:

```xml
  <dependencies>
    <dependency>
      <groupId>de.gesellix</groupId>
      <artifactId>docker-client</artifactId>
      <version>2025-11-01T13-00-00-groovy-4</version>
    </dependency>
    <dependency>
      <groupId>com.squareup.okio</groupId>
      <artifactId>okio</artifactId>
      <version>3.16.2</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <version>2.0.17</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
```

<img width="3726" height="2890" alt="Image" src="https://github.com/user-attachments/assets/e709d121-9c16-496e-8cf4-8a7f3663f8f7" />

This change leverages Maven's priority on the "nearest" dependency version for okio and okio-jvm to pull 3.16.2.

Your hint about enforcing okio:3.15.0 is a similar fix, because any release starting with [okio:3.13.0](https://square.github.io/okio/changelog/#version-3130) provides the `okio.Socket okio.Okio.socket(java.net.Socket)` method.
You'll find, though, that some features of the docker-client on some api endpoints will only work with a [okio:3.16.0](https://square.github.io/okio/changelog/#version-3160) and newer. The relevant features are edge cases for the `/attach` and `/exec`  endpoints. YMMV.

So, long story short: can you confirm that your project is a Maven project and could you also verify that enforcing okio:3.16.2 would fix the error?

**Comment by dvallant** [comment]
First of all thank you for the quick response and investigation into this issue.

> So, long story short: can you confirm that your project is a Maven project and could you also verify that enforcing okio:3.16.2 would fix the error?

Yes, I can confirm both.

Adding okio:3.16.2 as a dependency changes the dependency graph from:
```
[INFO] +- de.gesellix:docker-client:jar:2025-11-01T13-00-00:compile
[INFO] |  +- de.gesellix:docker-remote-api-client:jar:2025-11-01T10-50-00:compile
[INFO] |  |  +- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:2.0.21:compile
[INFO] |  |  |  \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:2.0.21:compile
[INFO] |  |  +- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:jar:1.9.0:runtime
[INFO] |  |  |  \- org.jetbrains:annotations:jar:26.0.2:compile
[INFO] |  |  \- com.squareup.okhttp3:okhttp-jvm:jar:5.3.0:runtime
[INFO] |  +- de.gesellix:docker-remote-api-model-1-41:jar:2025-10-31T17-49-00:compile
[INFO] |  +- de.gesellix:docker-engine:jar:2025-10-31T18-10-00:compile
[INFO] |  +- de.gesellix:docker-compose:jar:2025-10-31T17-47-00:compile
[INFO] |  |  +- org.jetbrains.kotlin:kotlin-stdlib:jar:2.0.21:compile
[INFO] |  |  +- org.jetbrains.kotlin:kotlin-reflect:jar:2.0.21:runtime
[INFO] |  |  +- io.github.microutils:kotlin-logging-jvm:jar:3.0.5:runtime
[INFO] |  |  |  \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:2.0.21:runtime
[INFO] |  |  \- com.squareup.moshi:moshi-kotlin:jar:1.15.2:runtime
[INFO] |  +- com.squareup.moshi:moshi:jar:1.15.2:compile
[INFO] |  |  \- com.squareup.okio:okio-jvm:jar:3.7.0:compile
[INFO] |  +- com.squareup.okhttp3:okhttp:jar:5.3.0:compile
[INFO] |  +- de.gesellix:docker-filesocket:jar:2025-10-31T17-48-00:runtime
[INFO] |  |  +- com.kohlschutter.junixsocket:junixsocket-core:pom:2.10.1:runtime
[INFO] |  |  |  \- com.kohlschutter.junixsocket:junixsocket-native-common:jar:2.10.1:runtime
[INFO] |  |  \- com.kohlschutter.junixsocket:junixsocket-common:jar:2.10.1:runtime
[INFO] |  +- org.codehaus.groovy:groovy:jar:3.0.23:runtime
[INFO] |  +- org.codehaus.groovy:groovy-json:jar:3.0.23:runtime
[INFO] |  +- com.google.re2j:re2j:jar:1.8:runtime
[INFO] |  +- com.squareup.okio:okio:jar:3.16.2:runtime
[INFO] |  +- org.apache.commons:commons-compress:jar:1.27.1:compile
```

to:

```
[INFO] +- de.gesellix:docker-client:jar:2025-11-01T13-00-00:compile
[INFO] |  +- de.gesellix:docker-remote-api-client:jar:2025-11-01T10-50-00:compile
[INFO] |  |  +- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:2.0.21:compile
[INFO] |  |  |  \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:2.0.21:compile
[INFO] |  |  +- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:jar:1.9.0:runtime
[INFO] |  |  |  \- org.jetbrains:annotations:jar:26.0.2:compile
[INFO] |  |  \- com.squareup.okhttp3:okhttp-jvm:jar:5.3.0:runtime
[INFO] |  +- de.gesellix:docker-remote-api-model-1-41:jar:2025-10-31T17-49-00:compile
[INFO] |  +- de.gesellix:docker-engine:jar:2025-10-31T18-10-00:compile
[INFO] |  +- de.gesellix:docker-compose:jar:2025-10-31T17-47-00:compile
[INFO] |  |  +- org.jetbrains.kotlin:kotlin-stdlib:jar:2.0.21:compile
[INFO] |  |  +- org.jetbrains.kotlin:kotlin-reflect:jar:2.0.21:runtime
[INFO] |  |  +- io.github.microutils:kotlin-logging-jvm:jar:3.0.5:runtime
[INFO] |  |  |  \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:2.0.21:runtime
[INFO] |  |  \- com.squareup.moshi:moshi-kotlin:jar:1.15.2:runtime
[INFO] |  +- com.squareup.moshi:moshi:jar:1.15.2:compile
[INFO] |  +- com.squareup.okhttp3:okhttp:jar:5.3.0:compile
[INFO] |  +- de.gesellix:docker-filesocket:jar:2025-10-31T17-48-00:runtime
[INFO] |  |  +- com.kohlschutter.junixsocket:junixsocket-core:pom:2.10.1:runtime
[INFO] |  |  |  \- com.kohlschutter.junixsocket:junixsocket-native-common:jar:2.10.1:runtime
[INFO] |  |  \- com.kohlschutter.junixsocket:junixsocket-common:jar:2.10.1:runtime
[INFO] |  +- org.codehaus.groovy:groovy:jar:3.0.23:runtime
[INFO] |  +- org.codehaus.groovy:groovy-json:jar:3.0.23:runtime
[INFO] |  +- com.google.re2j:re2j:jar:1.8:runtime
[INFO] |  +- org.apache.commons:commons-compress:jar:1.27.1:compile
[INFO] |  \- org.bouncycastle:bcpkix-jdk18on:jar:1.81:compile
[INFO] |     \- org.bouncycastle:bcutil-jdk18on:jar:1.81:compile
[INFO] |        \- org.bouncycastle:bcprov-jdk18on:jar:1.81:compile
[INFO] +- com.squareup.okio:okio:jar:3.16.2:runtime
[INFO] |  \- com.squareup.okio:okio-jvm:jar:3.16.2:compile
```

I also tested the new release but the dependency tree for okio looks the same as in the previous release.

**Comment by gesellix** [comment]
Adding okio-jvm in docker-client and _not_ adding a direct dependency in a project using the docker-client seems to fix the issue:

<img width="3586" height="2402" alt="Image" src="https://github.com/user-attachments/assets/68009dbd-4a10-49b4-af3c-2a46ef090df9" />

Can you check the package with version `2025-11-13T20-29-52` or `2025-11-13T20-29-52-groovy-4` from GitHub Packages at https://github.com/gesellix/docker-client/packages/631509?

You would have to (temporarily) add github as Maven repository to your `~/.m2/settings.xml` like described at https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#authenticating-with-a-personal-access-token.

**Comment by dvallant** [comment]
I tested with `2025-11-13T20-29-52-groovy-4` (`2025-11-13T20-29-52` is not available as a github package) and now it works as expected :)

The dependency tree looks now as follows:
```
[INFO] +- de.gesellix:docker-client:jar:2025-11-13T20-29-52-groovy-4:compile
[INFO] |  +- de.gesellix:docker-remote-api-client:jar:2025-11-09T15-40-00:compile
[INFO] |  |  +- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:2.0.21:compile
[INFO] |  |  |  \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:2.0.21:compile
[INFO] |  |  +- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:jar:1.9.0:runtime
[INFO] |  |  |  \- org.jetbrains:annotations:jar:26.0.2:compile
[INFO] |  |  \- com.squareup.okhttp3:okhttp-jvm:jar:5.3.0:runtime
[INFO] |  +- de.gesellix:docker-remote-api-model-1-41:jar:2025-10-31T17-49-00:compile
[INFO] |  +- de.gesellix:docker-compose:jar:2025-10-31T17-47-00:compile
[INFO] |  |  +- org.jetbrains.kotlin:kotlin-stdlib:jar:2.0.21:compile
[INFO] |  |  +- org.jetbrains.kotlin:kotlin-reflect:jar:2.0.21:runtime
[INFO] |  |  +- io.github.microutils:kotlin-logging-jvm:jar:3.0.5:runtime
[INFO] |  |  |  \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:2.0.21:runtime
[INFO] |  |  \- com.squareup.moshi:moshi-kotlin:jar:1.15.2:runtime
[INFO] |  +- com.squareup.moshi:moshi:jar:1.15.2:compile
[INFO] |  +- com.squareup.okhttp3:okhttp:jar:5.3.0:compile
[INFO] |  +- de.gesellix:docker-filesocket:jar:2025-10-31T17-48-00:runtime
[INFO] |  |  +- com.kohlschutter.junixsocket:junixsocket-core:pom:2.10.1:runtime
[INFO] |  |  |  \- com.kohlschutter.junixsocket:junixsocket-native-common:jar:2.10.1:runtime
[INFO] |  |  \- com.kohlschutter.junixsocket:junixsocket-common:jar:2.10.1:runtime
[INFO] |  +- org.apache.groovy:groovy-json:jar:4.0.24:runtime
[INFO] |  +- com.google.re2j:re2j:jar:1.8:runtime
[INFO] |  +- com.squareup.okio:okio:jar:3.16.2:runtime
[INFO] |  +- com.squareup.okio:okio-jvm:jar:3.16.2:compile
[INFO] |  \- org.apache.commons:commons-compress:jar:1.27.1:compile
```

**Comment by dvallant** [comment]
Thx :)
